# Generated by Django 4.1.7 on 2023-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.CharField(max_length=100),
        ),
    ]
